import React, { useState } from 'react';
import { useAuthStore } from '../store/authStore';
import { useGuestStore } from '../store/guestStore';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { Badge } from '../components/ui/badge';
import { QrCode, UserPlus, Mail, ShieldCheck, Calendar, Car, ArrowRight, Download, CheckCircle2, History, X } from 'lucide-react';
import { toast } from 'sonner';
import { VoiceInput } from '../components/ui/VoiceInput';

export default function GuestInvite() {
  const { user } = useAuthStore();
  const { invites, addInvite, removeInvite } = useGuestStore();
  const [step, setStep] = useState(1);
  const [guestInfo, setGuestInfo] = useState({ name: '', email: '', date: '', vehicle: '', purpose: '' });
  const [generatedQR, setGeneratedQR] = useState(null);

  const handleGenerate = (e) => {
    e.preventDefault();
    const qrData = {
      ...guestInfo,
      flat: user?.unit || 'N/A',
      resident: user?.name || 'Resident',
      qrCode: `SS-${Math.random().toString(36).substr(2, 9).toUpperCase()}`,
    };
    
    setGeneratedQR(qrData);
    setStep(2);
    toast.success("Security QR Code generated by AI!");
  };

  const handleSendEmail = () => {
    toast.promise(
      new Promise((resolve) => setTimeout(resolve, 2000)),
      {
        loading: `Encrypting and sending QR to ${guestInfo.email}...`,
        success: () => {
          addInvite(generatedQR);
          return `Invite sent successfully to ${guestInfo.name} at ${guestInfo.email}!`;
        },
        error: 'Failed to send invite',
      }
    );
  };

  return (
    <div className="p-4 md:p-6 space-y-8 max-w-4xl mx-auto pb-20">
      <div className="flex justify-between items-center">
        <div>
           <h1 className="text-3xl font-black tracking-tight flex items-center gap-3">
              <div className="bg-blue-500/10 p-2 rounded-xl text-blue-600">
                 <UserPlus className="h-8 w-8" />
              </div>
              Guest Entry Pass
           </h1>
           <p className="text-muted-foreground text-sm font-medium">Generate pre-approved QR passes for your visitors</p>
        </div>
        <Button variant="outline" className="gap-2 font-bold" onClick={() => setStep(step === 3 ? 1 : 3)}>
           <History className="h-4 w-4" /> My Invites
        </Button>
      </div>

      {step === 1 && (
        <Card className="shadow-2xl border-blue-500/10 animate-in fade-in slide-in-from-bottom-4">
           <CardHeader className="bg-blue-500/5 border-b">
              <CardTitle>Guest Information</CardTitle>
              <CardDescription>Enter guest details to generate a secure entry pass</CardDescription>
           </CardHeader>
           <CardContent className="pt-6">
              <form onSubmit={handleGenerate} className="space-y-6">
                 <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="space-y-2">
                       <Label className="font-bold">Guest Full Name</Label>
                       <Input required value={guestInfo.name} onChange={e => setGuestInfo({...guestInfo, name: e.target.value})} placeholder="e.g. Robert Fox" />
                    </div>
                    <div className="space-y-2">
                       <Label className="font-bold">Guest Email Address</Label>
                       <Input required type="email" value={guestInfo.email} onChange={e => setGuestInfo({...guestInfo, email: e.target.value})} placeholder="guest@example.com" />
                    </div>
                    <div className="space-y-2">
                       <Label className="font-bold">Arrival Date</Label>
                       <Input required type="date" value={guestInfo.date} onChange={e => setGuestInfo({...guestInfo, date: e.target.value})} />
                    </div>
                    <div className="space-y-2">
                       <Label className="font-bold">Vehicle Number (Optional)</Label>
                       <Input value={guestInfo.vehicle} onChange={e => setGuestInfo({...guestInfo, vehicle: e.target.value})} placeholder="e.g. MH 12 AB 1234" />
                    </div>
                    <div className="space-y-2 md:col-span-2">
                       <div className="flex justify-between items-center">
                          <Label className="font-bold">Purpose of Visit</Label>
                          <VoiceInput onResult={(text) => setGuestInfo({...guestInfo, purpose: text})} />
                       </div>
                       <Input required value={guestInfo.purpose} onChange={e => setGuestInfo({...guestInfo, purpose: e.target.value})} placeholder="e.g. Family Dinner" />
                    </div>
                 </div>
                 <Button type="submit" className="w-full bg-blue-600 hover:bg-blue-700 h-12 font-black shadow-xl shadow-blue-500/20">
                    GENERATE SMART PASS <ArrowRight className="ml-2 h-5 w-5" />
                 </Button>
              </form>
           </CardContent>
        </Card>
      )}

      {step === 2 && generatedQR && (
         <div className="grid md:grid-cols-2 gap-8 animate-in zoom-in-95 duration-300">
            <Card className="bg-gradient-to-br from-indigo-600 to-blue-700 text-white shadow-2xl border-none overflow-hidden h-fit">
               <CardHeader className="text-center border-b border-white/20 pb-6">
                  <div className="bg-white text-blue-600 w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-inner">
                     <QrCode className="h-10 w-10" />
                  </div>
                  <CardTitle className="text-2xl font-black">SOCIETY PASS</CardTitle>
                  <CardDescription className="text-white/70 font-bold uppercase tracking-[0.2em]">{generatedQR.qrCode}</CardDescription>
               </CardHeader>
               <CardContent className="p-8 space-y-6">
                  <div className="aspect-square bg-white rounded-3xl p-6 flex flex-col items-center justify-center shadow-2xl relative overflow-hidden group">
                     {/* REAL QR CODE GENERATION */}
                     <img 
                        src={`https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(
                          `PASS:${generatedQR.qrCode}|N:${generatedQR.name}|F:${generatedQR.flat}|V:${generatedQR.vehicle || 'NA'}|D:${generatedQR.date}`
                        )}`}
                        alt="Scannable Security Pass"
                        className="w-full h-full object-contain mix-blend-multiply"
                     />
                     <div className="absolute inset-x-0 bottom-4 text-center">
                        <Badge className="bg-black text-white px-4 py-1 text-[10px] font-black tracking-widest uppercase">Verified by AI</Badge>
                     </div>
                  </div>
                  <div className="grid grid-cols-2 gap-4 text-xs font-bold uppercase tracking-widest border-t border-white/10 pt-6">
                     <div>
                        <p className="opacity-60 mb-1 leading-none">Guest</p>
                        <p className="text-sm truncate">{generatedQR.name}</p>
                     </div>
                     <div className="text-right">
                        <p className="opacity-60 mb-1 leading-none">Email</p>
                        <p className="text-sm truncate">{generatedQR.email}</p>
                     </div>
                     <div className="mt-4">
                        <p className="opacity-60 mb-1 leading-none">Destination</p>
                        <p className="text-sm truncate">Flat {generatedQR.flat}</p>
                     </div>
                     <div className="mt-4 text-right">
                        <p className="opacity-60 mb-1 leading-none">Host</p>
                        <p className="text-sm truncate">{generatedQR.resident}</p>
                     </div>
                  </div>
               </CardContent>
               <CardFooter className="bg-black/20 p-4 gap-3">
                  <Button variant="ghost" className="flex-1 text-white hover:bg-white/10 font-bold" onClick={() => setStep(1)}>CANCEL</Button>
                  <Button className="flex-1 bg-white text-blue-700 hover:bg-zinc-100 font-black h-11 transition-all active:scale-95 shadow-lg group" onClick={handleSendEmail}>
                     <Mail className="mr-2 h-4 w-4 group-hover:animate-bounce" /> SEND PASS
                  </Button>
               </CardFooter>
            </Card>

            <div className="space-y-6">
               <Card className="border-emerald-500/20 shadow-lg bg-emerald-50/50">
                  <CardHeader>
                     <CardTitle className="text-emerald-700 flex items-center gap-2">
                        <ShieldCheck className="h-5 w-5" /> Security Protocol
                     </CardTitle>
                  </CardHeader>
                  <CardContent className="text-sm text-emerald-800 space-y-4">
                     <p className="font-medium">This pass will be sent directly to <strong>{generatedQR.email}</strong> once you click send.</p>
                     <ul className="space-y-3">
                        <li className="flex gap-3">
                           <CheckCircle2 className="h-5 w-5 shrink-0 opacity-40" />
                           <span>Guard will scan this QR at the entrance for instant verification.</span>
                        </li>
                        <li className="flex gap-3">
                           <CheckCircle2 className="h-5 w-5 shrink-0 opacity-40" />
                           <span>The guest will receive a secure link containing their entry code.</span>
                        </li>
                     </ul>
                  </CardContent>
               </Card>
               <Button variant="outline" className="w-full h-12 gap-2 border-dashed border-2 hover:bg-muted font-bold text-muted-foreground">
                  <Download className="h-5 w-5" /> Save to Device Gallery
               </Button>
            </div>
         </div>
      )}

      {step === 3 && (
         <Card className="shadow-xl">
            <CardHeader className="bg-muted/50 border-b flex flex-row justify-between items-center">
               <div>
                  <CardTitle>Invitation History</CardTitle>
                  <CardDescription>Manage your recent pre-approved visitors</CardDescription>
               </div>
               <Button variant="ghost" size="icon" onClick={() => setStep(1)}><X className="h-5 w-5" /></Button>
            </CardHeader>
            <CardContent className="p-0">
               {invites.length > 0 ? (
                  <div className="divide-y">
                     {invites.map((inv) => (
                        <div key={inv.id} className="p-4 flex items-center justify-between hover:bg-muted/30 transition-colors">
                           <div className="flex items-center gap-4">
                              <div className="bg-blue-100 text-blue-600 p-3 rounded-full">
                                 <UserPlus className="h-5 w-5" />
                              </div>
                              <div>
                                 <h4 className="font-bold">{inv.name}</h4>
                                 <div className="flex flex-wrap gap-3 text-xs text-muted-foreground font-medium mt-1">
                                    <span className="flex items-center gap-1 font-black text-blue-600">{inv.email}</span>
                                    <span className="flex items-center gap-1"><Calendar className="h-3 w-3" /> {inv.date}</span>
                                    <span className="flex items-center gap-1"><Car className="h-3 w-3" /> {inv.vehicle || 'Walking'}</span>
                                 </div>
                              </div>
                           </div>
                           <div className="flex items-center gap-4">
                              <Badge className="bg-emerald-500">{inv.status}</Badge>
                              <Button variant="ghost" size="icon" className="text-red-500 hover:bg-red-50" onClick={() => removeInvite(inv.id)}>
                                 <X className="h-4 w-4" />
                              </Button>
                           </div>
                        </div>
                     ))}
                  </div>
               ) : (
                  <div className="py-24 text-center opacity-30">
                     <Mail className="h-16 w-16 mx-auto mb-4" />
                     <p className="font-black uppercase tracking-[0.3em]">No Invitation Records</p>
                  </div>
               )}
            </CardContent>
         </Card>
      )}
    </div>
  );
}
